version: 2.1

commands:
  terraform:
    description: Plan and apply a Terraform configuration
    parameters:
      path:
        type: string
        default: terraform
    steps:
      - checkout
      - run: terraform init -input=false -backend-config="bucket=wishlist-terraform-state" -backend-config="key=terraform.tfstate" << parameters.path >>
      - run: terraform plan -input=false -out terraform.plan << parameters.path >>
      - run: terraform apply terraform.plan

orbs:
  aws-s3: circleci/aws-s3@3.0.0
  aws-cli: circleci/aws-cli@2.0.6
  terraform: circleci/terraform@3.0.1

jobs:
  build_api:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - wishlist-api-dependencies-{{ checksum "wishlist-api/package.json" }}
            - wishlist-api-dependencies-
      - run:
          command: yarn install
          working_directory: wishlist-api
      - save_cache:
          paths:
            - node_modules
          key: wishlist-api-dependencies-{{ checksum "wishlist-api/package.json" }}
      - run:
          command: yarn format-check
          working_directory: wishlist-api
      - run:
          command: yarn package
          working_directory: wishlist-api
      - persist_to_workspace:
          root: wishlist-api
          paths: dist/

  terraform:
    executor: aws-cli/default
    steps:
      - checkout
      - attach_workspace:
          at: wishlist-api
      - terraform/install:
          terraform_version: 0.12.24
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
      - terraform/init:
          backend: true
          backend_config: bucket=wishlist-terraform-state,key=terraform.tfstate
          path: terraform
      - terraform/plan:
          path: terraform
      - terraform/apply:
          path: terraform

  deploy_ui:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - aws-cli/install
      - attach_workspace:
          at: ~/.aws
      - restore_cache:
          keys:
            - ui-dependencies-{{ checksum "wishlist-ui/package.json" }}
            - ui-dependencies-
      - run:
          command: yarn install
          working_directory: wishlist-ui
      - save_cache:
          paths:
            - wishlist-ui/node_modules
          key: ui-dependencies-{{ checksum "wishlist-ui/package.json" }}
      - run:
          command: yarn build
          working_directory: wishlist-ui
      - aws-s3/sync:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
          from: wishlist-ui/build
          to: s3://budjb-wishlist-ui/

workflows:
  release:
    jobs:
      - build_api:
          filters:
            branches:
              only:
                - master
      - terraform:
          context: aws-personal
          requires:
            - build_api
          filters:
            branches:
              only:
                - master
      - deploy_ui:
          context: aws-personal
          filters:
            branches:
              only:
                - master
