version: 2.1

commands:
  terraform:
    description: Plan and apply a Terraform configuration
    parameters:
      path:
        type: string
        default: terraform
    steps:
      - run:
          name: Initialize Terraform
          command: terraform init -input=false -backend-config="bucket=wishlist-terraform-state" -backend-config="key=terraform.tfstate"
          working_directory: << parameters.path >>
      - run:
          name: Create Terraform Plan
          command: terraform plan -input=false -out terraform.plan
          working_directory: << parameters.path >>
      - run:
          name: Apply Terraform Plan
          command: terraform apply terraform.plan
          working_directory: << parameters.path >>

orbs:
  aws-s3: circleci/aws-s3@3.0.0
  aws-cli: circleci/aws-cli@2.0.6
  terraform: circleci/terraform@3.2.0

jobs:
  build_api:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: Update apt
          command: apt-get update
      - run:
          name: Install zip
          command: apt-get install -y zip
      - run:
          name: Install Python Dependencies
          command: pip install -r dev-requirements.txt
          working_directory: wishlist-api
      - run:
          name: Create Lambda Python Package
          command: invoke package
          working_directory: wishlist-api
      - persist_to_workspace:
          root: wishlist-api
          paths: build/dist/

  terraform:
    executor: aws-cli/default
    steps:
      - checkout
      - attach_workspace:
          at: wishlist-api
      - terraform/install:
          terraform_version: 1.3.7 
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
      - terraform

  deploy_ui:
    docker:
      - image: node:19
    steps:
      - checkout
      - aws-cli/install
      - attach_workspace:
          at: ~/.aws
      - restore_cache:
          keys:
            - ui-dependencies-{{ checksum "wishlist-ui/package.json" }}
            - ui-dependencies-
      - run:
          name: Install Node.js Dependencies
          command: yarn install
          working_directory: wishlist-ui
      - save_cache:
          paths:
            - wishlist-ui/node_modules
          key: ui-dependencies-{{ checksum "wishlist-ui/package.json" }}
      - run:
          name: Build React App
          command: yarn build
          working_directory: wishlist-ui
      - aws-s3/sync:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
          from: wishlist-ui/dist
          to: s3://budjb-wishlist-ui/

workflows:
  release:
    jobs:
      - build_api:
          filters:
            branches:
              only:
                - master
      - terraform:
          context: aws-personal
          requires:
            - build_api
          filters:
            branches:
              only:
                - master
      - deploy_ui:
          context: aws-personal
          filters:
            branches:
              only:
                - master
