version: 2.1

commands:
  terraform:
    description: Plan and apply a Terraform configuration
    parameters:
      path:
        type: string
        default: terraform
    steps:
      - checkout
      - run: terraform init -input=false -backend-config="bucket=wishlist-terraform-state" -backend-config="key=terraform.tfstate" << parameters.path >>
      - run: terraform plan -input=false -out terraform.plan << parameters.path >>
      - run: terraform apply terraform.plan

orbs:
  aws-cli: circleci/aws-cli@0.1.13

jobs:
  build_api:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - wishlist-api-dependencies-{{ checksum "wishlist-api/package.json" }}
            - wishlist-api-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: wishlist-api-dependencies-{{ checksum "wishlist-api/package.json" }}
      - run: yarn format-check
      - run: yarn package
      - persist_to_workspace:
          root: wishlist-api
          paths: dist/

  aws_auth:
    executor: aws-cli/default
    environment:
      AWS_REGION: us-east-1
    steps:
      - checkout
      - aws-cli/install
      - aws-cli/configure:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
      - persist_to_workspace:
          root: ~/.aws
          paths:
            - "*"

  terraform:
    docker:
      - image: hashicorp/terraform:0.12.24
    steps:
      - checkout
      - attach_workspace:
          at: ~/.aws
      - attach_workspace:
          at: wishlist-api
      - terraform

workflows:
  release:
    jobs:
      - aws_auth:
          context: aws-personal
          filters:
            branches:
              only:
                - master
      - build_api:
          filters:
            branches:
              only:
                - master
      - terraform:
          requires:
            - aws_auth
            - build_api
          filters:
            branches:
              only:
                - master
